import { env } from './env';
import * as backend from './backendApi';
import * as mock from './mockApi';
const adapter = env.useMockApi ? mock : backend;

export const getServices = adapter.getServices;
export const getServiceById = adapter.getServiceById;
export const getSiteContent = adapter.getSiteContent;
export const createBookingRequest = adapter.createBookingRequest;
export const getHorses = adapter.getHorses;
export const getTrainers = adapter.getTrainers;
export const createHorse = adapter.createHorse;
export const updateHorse = adapter.updateHorse;
export const deleteHorse = adapter.deleteHorse;
export const getBookings = adapter.getBookings;
export const getBookingById = adapter.getBookingById;
export const updateBookingStatus = adapter.updateBookingStatus;
export const assignBookingHorses = adapter.assignBookingHorses;
export const assignBookingTrainer = adapter.assignBookingTrainer;
export const updateBookingTrainerStatus = adapter.updateBookingTrainerStatus;
export const getAvailability = adapter.getAvailability;
export const checkAvailability = adapter.checkAvailability;
export const getBookingRules = adapter.getBookingRules;
export const createBookingRule = adapter.createBookingRule;
export const updateBookingRule = adapter.updateBookingRule;
export const deleteBookingRule = adapter.deleteBookingRule;
export const getScheduleExceptions = adapter.getScheduleExceptions;
export const getAvailableBookingDates = adapter.getAvailableBookingDates;
export const getReviews = adapter.getReviews;
export const getGalleryItems = adapter.getGalleryItems;
export const getContacts = adapter.getContacts;
export const getRules = adapter.getRules;
export const saveContacts = adapter.saveContacts;
export const saveReviews = adapter.saveReviews;
export const saveRules = adapter.saveRules;
